
name: connect_app
description: Connect â€“ real-time chat application (MVC).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  socket_io_client: ^2.0.3+1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/app_config.json
    - assets/config/app_config.example.json
